udp_bridge_node:
  ros__parameters:
    # Set to nuc host IP.
    peer_ip: "192.168.1.66"
    tx_port: 20000
    rx_port: 20000
    bind_ip: "0.0.0.0"

    # Jetson role: send /joint_states, receive /autoaim/target.
    send_joint_states: true
    recv_joint_states: false
    send_autoaim_target: false
    recv_autoaim_target: true
    
